export const name = "FEED";

export const ActionTypes = {
  CONNECTION_START: `${name}/CONNECTION_START`,
  CONNECTION_SUCCESS: `${name}/CONNECTION_SUCCESS`,
  CONNECTION_ERROR: `${name}/CONNECTION_ERROR`,
  CONNECTION_CLOSED: `${name}/CONNECTION_CLOSED`,
  GET_ORDERS: `${name}/GET_ORDERS`,
  SEND_ORDERS: `${name}/SEND_ORDERS`,
};
